name: cd-ebola-qr-bot-dev

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.x"]

    steps:
      - uses: actions/checkout@v3

      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Create JSON secret
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "secret.dev.json"
          json: ${{ secrets.CONFIG_FILE_DEV }}
          dir: "/"

      - name: Deploy to Cloudflare
        run: npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_DEV }}
